// Auto-generated by colors.py

import 'dart:ui';

const accentColors = [
  Color(0xfffff5cc),
  Color(0xfffff1cc),
  Color(0xffffefcc),
  Color(0xfffff1cc),
  Color(0xffffdbcc),
  Color(0xffffefcc),
  Color(0xfffbffcc),
  Color(0xffe8ffcc),
  Color(0xffd5ffcc),
  Color(0xffccffd5),
  Color(0xffccffe8),
  Color(0xffccfffb),
  Color(0xffccefff),
  Color(0xfffff3cc),
  Color(0xfffffecc),
  Color(0xffe2ccff),
];

const primaryColors = [
  Color(0xffffd474), // contrast ratio 5.82456471142964
  Color(0xff4d3c00), // contrast ratio 5.131551048194216
  Color(0xffd0c187), // contrast ratio 5.529257614713291
  Color(0xffd5212a), // contrast ratio 5.644652409710161
  Color(0xffa53300), // contrast ratio 5.272019425653915
  Color(0xff845a00), // contrast ratio 5.3249027529793045
  Color(0xff747b00), // contrast ratio 4.4056160670194595
  Color(0xff457b00), // contrast ratio 4.759500600587007
  Color(0xff177b00), // contrast ratio 4.872864221074725
  Color(0xff007b17), // contrast ratio 4.856003928836115
  Color(0xff007b45), // contrast ratio 4.816518785663914
  Color(0xff007b73), // contrast ratio 4.6801442121694015
  Color(0xff006694), // contrast ratio 5.179720075231227
  Color(0xff0033a5), // contrast ratio 7.478914206842744
  Color(0xff0a00a5), // contrast ratio 8.795416386639062
  Color(0xff4800a5), // contrast ratio 7.838426705632426
];
